server:
  port: 80
  servlet:
    context-path: /

#数据源配置
spring:
  datasource:
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/etcp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
    #配置文件地址以及后缀
  freemarker:
    template-loader-path: /WEB-INF/
    suffix: .html
    
    
      
#mybatis-plush配置
mybatis-plus:
    #配置别名包
  type-aliases-package: com.tedu.ETCP.pojo
    #配置mapper映射
  mapper-locations: classpath:/mybatis/mappers/*.xml
    #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    
#日志输出
logging:
  level:
    com.jt.mapper: debug